### ISSUE TITLE
AttributeError after relaying failed

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-server-python#13]
Just managed to trigger an internal server error:

```python
[2016-07-12 15:37:09.292546] INFO: saltyrtc.path.828.client.805ea2ea8: Connection established
[2016-07-12 15:37:09.859110] INFO: saltyrtc.path.828.client.805ea2ea8.0x02: Handshake completed
[2016-07-12 15:37:10.394731] INFO: saltyrtc.path.828.client.805ea2ea8.0x02: Sending relayed message failed, receiver 0x01 is gone
[2016-07-12 15:37:10.395454] INFO: saltyrtc.path.828.client.805ea2ea8.0x02: Relaying failed, enqueuing send-error
[2016-07-12 15:37:10.405469] INFO: saltyrtc.path.828.client.805ea2ea8.0x02: Sending relayed message failed, receiver 0x01 is gone
[2016-07-12 15:37:10.406046] INFO: saltyrtc.path.828.client.805ea2ea8.0x02: Relaying failed, enqueuing send-error
[2016-07-12 15:37:10.410673] ERROR: saltyrtc.path.828.client.805ea2ea8.0x02: Closing due to exception:
Traceback (most recent call last):
  File "/usr/home/lg/saltyrtc-server-python/saltyrtc/server.py", line 133, in handler
    yield from self.handle_client()
  File "/usr/home/lg/saltyrtc-server-python/saltyrtc/server.py", line 227, in handle_client
    raise exc
  File "/usr/local/lib/python3.4/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/home/lg/saltyrtc-server-python/saltyrtc/server.py", line 397, in responder_receive_loop
    yield from self.relay_message(initiator, message)
  File "/usr/home/lg/saltyrtc-server-python/saltyrtc/server.py", line 422, in relay_message
    source.log.info(error_message, destination.id)
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by lgrahl** [comment]
Two questions (just to be sure that `send-error` is working correctly):

1. Did the client actually send two relay messages?
2. Did the client receive the two send-error messages?

**Comment by lgrahl** [comment]
Should be fixed in `develop` branch. Reopen if it occurs again.

**Comment by dbrgn** [comment]
Thanks!
