### ISSUE TITLE
Task exception never retrieved: Disconnected

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-server-python#55]
```
[2017-07-06 11:30:25.653956] ERROR: asyncio: Task exception was never retrieved
future: <Task finished coro=<responder_receive_loop() done, defined at /.../saltyrtc-server-python
/saltyrtc/server/server.py:495> exception=Disconnected(1006,)>
Traceback (most recent call last):
  File "/.../saltyrtc-server-python/saltyrtc/server/protocol.py", line 528, in receive
    data = yield from self._connection.recv()
  File "/.../.virtualenvs/saltyrtc-py34/lib/python3.4/site-packages/websockets/protocol.py", line 299, in r
ecv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006, no reason.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.../python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/.../saltyrtc-server-python/saltyrtc/server/server.py", line 500, in responder_receive_loo
p
    message = yield from responder.receive()
  File "/.../saltyrtc-server-python/saltyrtc/server/protocol.py", line 531, in receive
    raise Disconnected(exc.code) from exc
saltyrtc.server.exception.Disconnected: 1006
```

**Comment by lgrahl** [comment]
Closing this. Can be reopened when it reoccurs.
