### ISSUE TITLE
test_drop_responder results in uncaught exception

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-server-python#70]
Even though it doesn't affect the test, the exception needs to be caught:

```
.[2018-02-28 17:34:08.236700] ERROR: asyncio: Task exception was never retrieved
future: <Task finished coro=<ServerProtocol.responder_receive_loop() done, defined at /saltyrtc/saltyrtc-server-python/saltyrtc/server/server.py:522> exception=Disconnected(1000,)>
Traceback (most recent call last):
  File "/saltyrtc/saltyrtc-server-python/saltyrtc/server/protocol.py", line 528, in receive
    data = yield from self._connection.recv()
  File "/.virtualenvs/saltyrtc-server-py35/lib/python3.5/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/saltyrtc/saltyrtc-server-python/saltyrtc/server/server.py", line 527, in responder_receive_loop
    message = yield from responder.receive()
  File "/saltyrtc/saltyrtc-server-python/saltyrtc/server/protocol.py", line 531, in receive
    raise Disconnected(exc.code) from exc
saltyrtc.server.exception.Disconnected: 1000
```

**Comment by lgrahl** [comment]
There are a number of other tests that produce similar issues (all related to disconnects):
- test_relay_errors
- test_relay_encrypted
- test_relay_receiver_offline
- test_explicit_permanent_key_unavailable
