### ISSUE TITLE
Disconnected exception not caught

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-server-python#80]
I found this in the log:

```
Jul 31 10:07:35 vs-wcs2 python[6075]: future: <Task finished coro=<ServerProtocol.initiator_receive_loop() done, defined at /srv/saltyrtc-server/saltyrtc/server/server.py:536> exception=Disconnected(3003,) created at /srv/saltyrtc-server/saltyrtc/server/server.py:368>
Jul 31 10:07:35 vs-wcs2 python[6075]: source_traceback: Object created at (most recent call last):
Jul 31 10:07:35 vs-wcs2 python[6075]:   File "start_saltyrtc.py", line 115, in <module>
Jul 31 10:07:35 vs-wcs2 python[6075]:     main()
Jul 31 10:07:35 vs-wcs2 python[6075]:   File "start_saltyrtc.py", line 91, in main
Jul 31 10:07:35 vs-wcs2 python[6075]:     loop.run_forever()
Jul 31 10:07:35 vs-wcs2 python[6075]:   File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
Jul 31 10:07:35 vs-wcs2 python[6075]:     self._run_once()
Jul 31 10:07:35 vs-wcs2 python[6075]:   File "/usr/lib/python3.5/asyncio/base_events.py", line 1304, in _run_once
Jul 31 10:07:35 vs-wcs2 python[6075]:     handle._run()
Jul 31 10:07:35 vs-wcs2 python[6075]:   File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
Jul 31 10:07:35 vs-wcs2 python[6075]:     self._callback(*self._args)
Jul 31 10:07:35 vs-wcs2 python[6075]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 307, in _wakeup
Jul 31 10:07:35 vs-wcs2 python[6075]:     self._step()
Jul 31 10:07:35 vs-wcs2 python[6075]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
Jul 31 10:07:35 vs-wcs2 python[6075]:     result = coro.send(None)
Jul 31 10:07:35 vs-wcs2 python[6075]:   File "/srv/saltyrtc-server/saltyrtc/server/server.py", line 216, in handler
Jul 31 10:07:35 vs-wcs2 python[6075]:     yield from self.handle_client(task_loop_task)
Jul 31 10:07:35 vs-wcs2 python[6075]:   File "/srv/saltyrtc-server/saltyrtc/server/server.py", line 368, in handle_client
Jul 31 10:07:35 vs-wcs2 python[6075]:     for coroutine in coroutines]
Jul 31 10:07:35 vs-wcs2 python[6075]:   File "/srv/saltyrtc-server/saltyrtc/server/server.py", line 368, in <listcomp>
Jul 31 10:07:35 vs-wcs2 python[6075]:     for coroutine in coroutines]
Jul 31 10:07:35 vs-wcs2 python[6075]: Traceback (most recent call last):
Jul 31 10:07:35 vs-wcs2 python[6075]:   File "/srv/saltyrtc-server/saltyrtc/server/protocol.py", line 559, in receive
Jul 31 10:07:35 vs-wcs2 python[6075]:     data = yield from self._connection.recv()
Jul 31 10:07:35 vs-wcs2 python[6075]:   File "/var/venv/saltyrtc-server/lib/python3.5/site-packages/websockets/protocol.py", line 298, in recv
Jul 31 10:07:35 vs-wcs2 python[6075]:     raise ConnectionClosed(self.close_code, self.close_reason)
Jul 31 10:07:35 vs-wcs2 python[6075]: websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 3003, no reason.
Jul 31 10:07:35 vs-wcs2 python[6075]: The above exception was the direct cause of the following exception:
Jul 31 10:07:35 vs-wcs2 python[6075]: Traceback (most recent call last):
Jul 31 10:07:35 vs-wcs2 python[6075]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
Jul 31 10:07:35 vs-wcs2 python[6075]:     result = coro.send(None)
Jul 31 10:07:35 vs-wcs2 python[6075]:   File "/srv/saltyrtc-server/saltyrtc/server/server.py", line 541, in initiator_receive_loop
Jul 31 10:07:35 vs-wcs2 python[6075]:     message = yield from initiator.receive()
Jul 31 10:07:35 vs-wcs2 python[6075]:   File "/srv/saltyrtc-server/saltyrtc/server/protocol.py", line 562, in receive
Jul 31 10:07:35 vs-wcs2 python[6075]:     raise Disconnected(exc.code) from exc
Jul 31 10:07:35 vs-wcs2 python[6075]: saltyrtc.server.exception.Disconnected: 3003
```

Version: 2.0.0

**Comment by dbrgn** [comment]
Another source: 

```
Aug 02 16:04:42 vs-wcs1 python[15007]: [2018-08-02 14:04:42.321779] ERROR: saltyrtc.path.51.client.7fc01556fcf0.0x02: Task loop returned with an exception: 3003
Aug 02 16:04:42 vs-wcs1 python[15007]: Traceback (most recent call last):
Aug 02 16:04:42 vs-wcs1 python[15007]:   File "/srv/saltyrtc-server/saltyrtc/server/protocol.py", line 547, in send
Aug 02 16:04:42 vs-wcs1 python[15007]:     yield from self._connection.send(data)
Aug 02 16:04:42 vs-wcs1 python[15007]:   File "/var/venv/saltyrtc-server/lib/python3.5/site-packages/websockets/protocol.py", line 309, in send
Aug 02 16:04:42 vs-wcs1 python[15007]:     yield from self.ensure_open()
Aug 02 16:04:42 vs-wcs1 python[15007]:   File "/var/venv/saltyrtc-server/lib/python3.5/site-packages/websockets/protocol.py", line 401, in ensure_open
Aug 02 16:04:42 vs-wcs1 python[15007]:     raise ConnectionClosed(self.close_code, self.close_reason)
Aug 02 16:04:42 vs-wcs1 python[15007]: websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 3003, no reason.
Aug 02 16:04:42 vs-wcs1 python[15007]: The above exception was the direct cause of the following exception:
Aug 02 16:04:42 vs-wcs1 python[15007]: Traceback (most recent call last):
Aug 02 16:04:42 vs-wcs1 python[15007]:   File "/srv/saltyrtc-server/saltyrtc/server/server.py", line 258, in handler
Aug 02 16:04:42 vs-wcs1 python[15007]:     loop=self._loop)
Aug 02 16:04:42 vs-wcs1 python[15007]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
Aug 02 16:04:42 vs-wcs1 python[15007]:     return fut.result()
Aug 02 16:04:42 vs-wcs1 python[15007]:   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
Aug 02 16:04:42 vs-wcs1 python[15007]:     raise self._exception
Aug 02 16:04:42 vs-wcs1 python[15007]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
Aug 02 16:04:42 vs-wcs1 python[15007]:     result = coro.send(None)
Aug 02 16:04:42 vs-wcs1 python[15007]:   File "/srv/saltyrtc-server/saltyrtc/server/server.py", line 530, in task_loop
Aug 02 16:04:42 vs-wcs1 python[15007]:     yield from task
Aug 02 16:04:42 vs-wcs1 python[15007]:   File "/srv/saltyrtc-server/saltyrtc/server/protocol.py", line 550, in send
Aug 02 16:04:42 vs-wcs1 python[15007]:     raise Disconnected(exc.code) from exc
Aug 02 16:04:42 vs-wcs1 python[15007]: saltyrtc.server.exception.Disconnected: 3003
```
